name: build
on: 
  pull_request:
    paths:
      - '.github/workflows/build.yml'
      - 'packages/{core,fetcher,sdk,e2e}/src/**'
      - 'packages/{core,fetcher,sdk,e2e}/package.json'
      - 'test/**'
      - 'test/package.json'
      - 'package.json'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: test
        working-directory: ./test
        run: | 
          pnpm install 
          pnpm start -- --skipBuild
