name: migrate
on:
  pull_request:
    paths:
      - '.github/workflows/migrate.yaml'
      - 'packages/migrate/assets/input/*.json'
      - 'packages/migrate/src/**'
      - 'packages/migrate/test/**'
      - 'packages/migrate/package.json'
jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup dependencies
        run: |
          pnpm install
          pnpm run build

      - name: Build
        working-directory: ./packages/migrate
        run: pnpm run build
        
      - name: test
        working-directory: ./packages/migrate
        run: pnpm run test
